sudo: required
language: generic 

services:
    - docker
    
before_install:
    - docker build -t kirtimansingh/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kirtimansingh/docker-react npm run test